### ISSUE TITLE
增加华为系统分享截图后删除

### ISSUE THREAD

**Issue by Sev73n** [1045290202/DeleteRecentPictures#1]
华为没有截图后删除的功能，能不能和这个软件联动一下 比如识别到截屏分享后 提示删除或者自动删除
或者更加智能一点 识别到分享到微信 或者某个特定的软件
就把刚刚的截屏删除
这样就不会被截屏污染相册了

**Comment by 1045290202** [comment]
我考虑一下，不确定能不能实现这个功能

**Comment by Sev73n** [comment]
> 我考虑一下，不确定能不能实现这个功能

十分感谢！提供个思路 或者 可以提供一个分享的功能 

就是系统截图了 然后选择分享到你的这个软件 
然后再通过你的软件分享到微信或者qq之类的地方 
分享成功了以后就可以通过你的软件把截图删除了
如果系统截图这个事件广播拿不到的话 可以曲线救国一下 

如果更加进一步的话 就是你的软件在分享菜单里提供一个分享控件
直接就是分享到微信后删除 一整个流水线操作
就可以一步到位了 可以先从分享到微信试试
甚至以后可以开会员收费 比如你想要 钉钉或者微博啥的一键分享删除 要花钱解锁
这样付费点还有了

华为苹果三星都没有这个功能 而小米魅族ov他们都上了
唉 人性化功能还是要靠你们这样厉害的开发者

**Comment by 1045290202** [comment]
> > 我考虑一下，不确定能不能实现这个功能
> 
> 十分感谢！提供个思路 或者 可以提供一个分享的功能 
> 
> 就是系统截图了 然后选择分享到你的这个软件 
> 然后再通过你的软件分享到微信或者qq之类的地方 
> 分享成功了以后就可以通过你的软件把截图删除了
> 如果系统截图这个事件广播拿不到的话 可以曲线救国一下 
> 
> 如果更加进一步的话 就是你的软件在分享菜单里提供一个分享控件
> 直接就是分享到微信后删除 一整个流水线操作
> 就可以一步到位了 可以先从分享到微信试试
> 甚至以后可以开会员收费 比如你想要 钉钉或者微博啥的一键分享删除 要花钱解锁
> 这样付费点还有了
> 
> 华为苹果三星都没有这个功能 而小米魅族ov他们都上了
> 唉 人性化功能还是要靠你们这样厉害的开发者

后面这个方法实现起来比较容易

**Comment by Sev73n** [comment]
> > > 我考虑一下，不确定能不能实现这个功能
> > 
> > 
> > 十分感谢！提供个思路 或者 可以提供一个分享的功能
> > 就是系统截图了 然后选择分享到你的这个软件
> > 然后再通过你的软件分享到微信或者qq之类的地方
> > 分享成功了以后就可以通过你的软件把截图删除了
> > 如果系统截图这个事件广播拿不到的话 可以曲线救国一下
> > 如果更加进一步的话 就是你的软件在分享菜单里提供一个分享控件
> > 直接就是分享到微信后删除 一整个流水线操作
> > 就可以一步到位了 可以先从分享到微信试试
> > 甚至以后可以开会员收费 比如你想要 钉钉或者微博啥的一键分享删除 要花钱解锁
> > 这样付费点还有了
> > 华为苹果三星都没有这个功能 而小米魅族ov他们都上了
> > 唉 人性化功能还是要靠你们这样厉害的开发者
> 
> 后面这个方法实现起来比较容易

好的 期待功能上线！
